In [2]:
import pandas as pd 
data = pd.read_csv("../Data/teen_screentime_addiction.csv") # Reading CSV file
df = pd.DataFrame(data)

In [3]:
#first 5 lines of Dataframe
df.head()

,ID,Name,Age,Gender,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
0,1,Shannon Francis,13,Female,Hansonfort,9th,4.0,6.1,78,5,...,1.4,86,19,3.6,1.7,1.2,Browsing,4,8.7,10.0
1,2,Scott Rodriguez,17,Female,Theodorefort,7th,5.5,6.5,70,5,...,0.9,96,9,1.1,4.0,1.8,Browsing,2,5.3,10.0
2,3,Adrian Knox,13,Other,Lindseystad,11th,5.8,5.5,93,8,...,0.5,137,8,0.3,1.5,0.4,Education,6,5.7,9.2
3,4,Brittany Hamilton,18,Female,West Anthony,12th,3.1,3.9,78,8,...,1.4,128,7,3.1,1.6,0.8,Social Media,8,3.0,9.8
4,5,Steven Smith,14,Other,Port Lindsaystad,9th,2.5,6.7,56,4,...,1.0,96,20,2.6,0.9,1.1,Gaming,10,3.7,8.6

In [4]:
#Summary of DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ID                      3000 non-null   int64
 1   Name                    3000 non-null   str
 2   Age                     3000 non-null   int64
 3   Gender                  3000 non-null   str
 4   Location                3000 non-null   str
 5   School_Grade            3000 non-null   str
 6   Daily_Usage_Hours       3000 non-null   float64
 7   Sleep_Hours             3000 non-null   float64
 8   Academic_Performance    3000 non-null   int64
 9   Social_Interactions     3000 non-null   int64
 10  Exercise_Hours          3000 non-null   float64
 11  Anxiety_Level           3000 non-null   int64
 12  Depression_Level        3000 non-null   int64
 13  Self_Esteem             3000 non-null   int64
 14  Parental_Control        3000 non-null   int64
 15  Screen_Time_Before_Bed  3000 non-null   float64
 16  Phone_Checks_Per_Day    3000 non-null   int64
 17  Apps_Used_Daily         3000 non-null   int64
 18  Time_on_Social_Media    3000 non-null   float64
 19  Time_on_Gaming          3000 non-null   float64
 20  Time_on_Education       3000 non-null   float64
 21  Phone_Usage_Purpose     3000 non-null   str
 22  Family_Communication    3000 non-null   int64
 23  Weekend_Usage_Hours     3000 non-null   float64
 24  Addiction_Level         3000 non-null   float64
dtypes: float64(9), int64(11), str(5)
memory usage: 586.1 KB

In [5]:
#find rows and columns
df.shape

(3000, 25)

In [6]:
#View Descriptive statistics
df.describe()

,ID,Age,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,Exercise_Hours,Anxiety_Level,Depression_Level,Self_Esteem,Parental_Control,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Family_Communication,Weekend_Usage_Hours,Addiction_Level
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,1500.500000,15.969667,5.020667,6.489767,74.947333,5.097667,1.040667,5.590000,5.460333,5.546333,0.507333,1.006733,83.093000,12.609333,2.499233,1.525267,1.016333,5.459667,6.015100,8.881900
std,866.169729,1.989489,1.956501,1.490713,14.684156,3.139333,0.734620,2.890678,2.871557,2.860754,0.500030,0.492878,37.747044,4.611486,0.988201,0.932701,0.648341,2.864572,2.014776,1.609598
min,1.000000,13.000000,0.000000,3.000000,50.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,20.000000,5.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000
25%,750.750000,14.000000,3.700000,5.500000,62.000000,2.000000,0.500000,3.000000,3.000000,3.000000,0.000000,0.700000,51.000000,9.000000,1.800000,0.800000,0.500000,3.000000,4.700000,8.000000
50%,1500.500000,16.000000,5.000000,6.500000,75.000000,5.000000,1.000000,6.000000,5.000000,6.000000,1.000000,1.000000,82.000000,13.000000,2.500000,1.500000,1.000000,5.000000,6.000000,10.000000
75%,2250.250000,18.000000,6.400000,7.500000,88.000000,8.000000,1.500000,8.000000,8.000000,8.000000,1.000000,1.400000,115.250000,17.000000,3.200000,2.200000,1.500000,8.000000,7.400000,10.000000
max,3000.000000,19.000000,11.500000,10.000000,100.000000,10.000000,4.000000,10.000000,10.000000,10.000000,1.000000,2.600000,150.000000,20.000000,5.000000,4.000000,3.000000,10.000000,14.000000,10.000000

In [7]:
#Categorical columns
df.value_counts()

ID    Name               Age  Gender  Location          School_Grade  Daily_Usage_Hours  Sleep_Hours  Academic_Performance  Social_Interactions  Exercise_Hours  Anxiety_Level  Depression_Level  Self_Esteem  Parental_Control  Screen_Time_Before_Bed  Phone_Checks_Per_Day  Apps_Used_Daily  Time_on_Social_Media  Time_on_Gaming  Time_on_Education  Phone_Usage_Purpose  Family_Communication  Weekend_Usage_Hours  Addiction_Level
1     Shannon Francis    13   Female  Hansonfort        9th           4.0                6.1          78                    5                    0.1             10             3                 8            0                 1.4                     86                    19               3.6                   1.7             1.2                Browsing             4                     8.7                  10.0               1
2     Scott Rodriguez    17   Female  Theodorefort      7th           5.5                6.5          70                    5                    0.0             3              7                 3            0                 0.9                     96                    9                1.1                   4.0             1.8                Browsing             2                     5.3                  10.0               1
3     Adrian Knox        13   Other   Lindseystad       11th          5.8                5.5          93                    8                    0.8             2              3                 10           0                 0.5                     137                   8                0.3                   1.5             0.4                Education            6                     5.7                  9.2                1
4     Brittany Hamilton  18   Female  West Anthony      12th          3.1                3.9          78                    8                    1.6             9              10                3            0                 1.4                     128                   7                3.1                   1.6             0.8                Social Media         8                     3.0                  9.8                1
5     Steven Smith       14   Other   Port Lindsaystad  9th           2.5                6.7          56                    4                    1.1             1              5                 1            0                 1.0                     96                    20               2.6                   0.9             1.1                Gaming               10                    3.7                  8.6                1
                                                                                                                                                                                                                                                                                                                                                                                                                                           ..
2996  Jesus Yates        16   Female  New Jennifer      12th          3.9                6.4          53                    4                    0.9             7              10                2            1                 0.3                     80                    15               2.7                   1.8             1.0                Other                8                     9.4                  9.8                1
2997  Bethany Murray     13   Female  Richardport       8th           3.6                7.3          93                    5                    0.0             8              8                 9            1                 0.9                     45                    8                3.1                   0.0             0.3                Gaming               9                     5.2                  5.5                1
2998  Norman Hughes      14   Other   Rebeccaton        7th           3.2                6.5          98                    1                    0.0             4              3                 9            0                 0.2                     51                    13               2.4                   0.2             2.4                Social Media         9                     5.9                  6.2                1
2999  Barbara Hinton     17   Female  Ramirezmouth      9th           6.7                7.5          67                    3                    0.2             3              5                 9            0                 1.6                     125                   17               1.7                   2.6             1.5                Browsing             4                     6.1                  10.0               1
3000  Curtis Johnson     17   Male    Lake Alexander    10th          3.5                6.9          79                    4                    2.1             4              5                 5            1                 0.6                     117                   8                0.0                   2.3             0.1                Education            7                     5.1                  6.3                1
Name: count, Length: 3000, dtype: int64

In [8]:
#filter with .loc
df.loc[df["Daily_Usage_Hours"] > 5, ["Name","Gender", "Age", "Daily_Usage_Hours"]]

                     Name  Gender  Age  Daily_Usage_Hours
1         Scott Rodriguez  Female   17                5.5
2             Adrian Knox   Other   13                5.8
6            Hailey Moses    Male   16                6.3
7       Veronica Marshall   Other   13                5.1
12           Sarah Nguyen  Female   19                7.4
...                   ...     ...  ...                ...
2988         Angela Lyons    Male   14                6.4
2989  Christine Davenport   Other   18                5.1
2991     Christina Davila    Male   16                6.3
2993       Sandra Acevedo   Other   17                9.0
2998       Barbara Hinton  Female   17                6.7

[1455 rows x 4 columns]

In [9]:
#Sleephours
df.loc[df["Sleep_Hours"] > 5, ["Name","Gender", "Age", "Daily_Usage_Hours"]]

                 Name  Gender  Age  Daily_Usage_Hours
0     Shannon Francis  Female   13                4.0
1     Scott Rodriguez  Female   17                5.5
2         Adrian Knox   Other   13                5.8
4        Steven Smith   Other   14                2.5
5          Mary Adams  Female   13                3.9
...               ...     ...  ...                ...
2995      Jesus Yates  Female   16                3.9
2996   Bethany Murray  Female   13                3.6
2997    Norman Hughes   Other   14                3.2
2998   Barbara Hinton  Female   17                6.7
2999   Curtis Johnson    Male   17                3.5

[2499 rows x 4 columns]

In [10]:
df.loc[(df['Gender'] == 'Male')]

,ID,Name,Age,Gender,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
6,7,Hailey Moses,16,Male,North Jeffrey,11th,6.3,6.7,89,3,...,0.8,129,9,1.8,2.7,1.0,Education,7,7.8,10.0
8,9,Edward Avila,13,Male,Leebury,8th,3.0,9.1,79,0,...,0.9,70,13,2.7,2.2,1.3,Education,10,9.1,7.3
11,12,Ruben Walters,14,Male,Lake Mary,11th,1.6,5.9,70,10,...,0.9,147,18,1.9,2.7,1.0,Browsing,7,3.2,9.8
19,20,Kathryn Perez,18,Male,South Thomas,12th,5.4,5.9,69,4,...,0.6,83,19,1.6,1.0,0.4,Browsing,7,6.1,10.0
23,24,Desiree Brady,19,Male,East Amanda,9th,6.9,3.6,79,5,...,0.8,32,7,2.0,1.3,1.2,Education,7,6.6,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,2980,Travis Harris,14,Male,East Mariastad,7th,8.7,7.1,98,7,...,1.7,94,16,3.4,1.9,1.3,Social Media,4,7.6,10.0
2982,2983,Luke Hamilton,14,Male,Ericland,9th,5.7,5.0,62,9,...,0.5,58,18,3.9,3.4,1.1,Other,2,5.0,10.0
2988,2989,Angela Lyons,14,Male,Howebury,7th,6.4,5.1,50,8,...,1.0,82,15,3.3,0.2,0.8,Education,10,7.5,10.0
2991,2992,Christina Davila,16,Male,Heatherfurt,11th,6.3,5.7,87,8,...,0.2,36,5,2.1,2.3,2.0,Social Media,8,6.6,9.6
2999,3000,Curtis Johnson,17,Male,Lake Alexander,10th,3.5,6.9,79,4,...,0.6,117,8,0.0,2.3,0.1,Education,7,5.1,6.3

In [11]:
#find null values
df.isnull().sum()

ID                        0
Name                      0
Age                       0
Gender                    0
Location                  0
School_Grade              0
Daily_Usage_Hours         0
Sleep_Hours               0
Academic_Performance      0
Social_Interactions       0
Exercise_Hours            0
Anxiety_Level             0
Depression_Level          0
Self_Esteem               0
Parental_Control          0
Screen_Time_Before_Bed    0
Phone_Checks_Per_Day      0
Apps_Used_Daily           0
Time_on_Social_Media      0
Time_on_Gaming            0
Time_on_Education         0
Phone_Usage_Purpose       0
Family_Communication      0
Weekend_Usage_Hours       0
Addiction_Level           0
dtype: int64

In [12]:
df.sort_values('Age')

,ID,Name,Age,Gender,Location,School_Grade,Daily_Usage_Hours,Sleep_Hours,Academic_Performance,Social_Interactions,...,Screen_Time_Before_Bed,Phone_Checks_Per_Day,Apps_Used_Daily,Time_on_Social_Media,Time_on_Gaming,Time_on_Education,Phone_Usage_Purpose,Family_Communication,Weekend_Usage_Hours,Addiction_Level
2987,2988,Miss Emily Jenkins DDS,13,Other,South Theresa,12th,6.0,7.0,55,7,...,1.1,134,14,2.1,1.1,2.0,Other,7,5.0,10.0
8,9,Edward Avila,13,Male,Leebury,8th,3.0,9.1,79,0,...,0.9,70,13,2.7,2.2,1.3,Education,10,9.1,7.3
7,8,Veronica Marshall,13,Other,Jenniferport,10th,5.1,6.1,70,2,...,1.0,34,7,2.3,1.6,0.5,Browsing,9,8.0,8.0
5,6,Mary Adams,13,Female,East Angelachester,10th,3.9,6.3,89,3,...,1.1,135,8,3.8,0.0,1.4,Social Media,7,6.0,8.8
464,465,Amber Rodriguez,13,Female,Stephaniestad,11th,5.4,4.3,93,2,...,1.0,38,20,3.5,3.4,0.9,Browsing,8,3.3,10.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,30,Jared Bridges,19,Other,Jessicaberg,11th,8.6,5.2,63,0,...,1.3,72,15,0.2,1.8,0.7,Browsing,9,6.6,10.0
27,28,Jeffrey Crawford,19,Male,Shawburgh,8th,4.9,9.3,50,4,...,0.3,117,5,3.5,4.0,0.9,Education,3,7.0,10.0
26,27,Kelly Giles,19,Male,West Kimberlyfurt,11th,6.2,4.5,65,3,...,1.1,115,10,2.1,1.6,1.0,Social Media,7,6.6,10.0
24,25,Mark Crawford,19,Other,Port Alan,12th,4.6,7.2,85,7,...,1.1,71,5,1.8,0.8,1.1,Social Media,8,6.2,6.0
23,24,Desiree Brady,19,Male,East Amanda,9th,6.9,3.6,79,5,...,0.8,32,7,2.0,1.3,1.2,Education,7,6.6,10.0

In [14]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Length: 3000, dtype: bool